[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "smfmodel"
description = "Probabalistic Modeling of Single Molecule Footprinting data in Python."
requires-python = ">=3.9"
license = "MIT"
authors = [
    {name = "Joseph McKenna"}
]
maintainers = [
    {name = "Joseph McKenna", email = "jkmckenna@berkeley.edu"}
]
keywords = [
  "single-molecule-footprinting",
  "chromatin-accessibility",
  "protein-dna-binding",
  "nanopore",
  "single-locus",
  "anndata",
  "machine-learning"
]
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: MacOS :: MacOS X",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Visualization"
]
dependencies = [
    "anndata>=0.10.0",
    "biopython>=1.79",
    "Cython>=0.29.28",
    "networkx>=3.2",
    "numpy>=1.22.0,<2",
    "pandas>=1.4.2",
    "scanpy>=1.9",
    "scikit-learn>=1.0.2",
    "scipy>=1.7.3",
    "seaborn>=0.11",
    "torch>=1.9.0",
    "tqdm"
]
dynamic = ["version"]

[project.urls]
Source = "https://github.com/jkmckenna/smfmodel"
Documentation = "https://smfmodel.readthedocs.io/"

[project.optional-dependencies]
tests = [
    "pytest",
    "pytest-cov"
]

docs = [
    "sphinx>=7",
    "sphinx-book-theme>=1.1.0",
    "sphinx-autodoc-typehints>=1.25.2",
    "myst-parser>=2",
    "myst-nb>=1",
    "sphinx-design",
    "readthedocs-sphinx-search",
    "sphinxext-opengraph",
    "sphinx-copybutton",
    "nbsphinx>=0.9",
    "ipython>=7.20",
    "matplotlib!=3.6.1",
    "sphinxcontrib-bibtex",
    "setuptools"
]

[tool.hatch.envs.default]
python = "3.9"
dependencies = ["pydantic"]

[tool.hatch.build.targets.wheel]
packages = ["src/smfmodel"]

[tool.hatch.version]
path = "src/smfmodel/_version.py"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "--strict-markers",
    "--doctest-modules",
    "--pyargs",
]
testpaths = ["tests"]
pythonpath = ["src"]
xfail_strict = true

[tool.coverage.run]
source = ["smfmodel"]
omit = ["tests/*"]